import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, CalendarDays, MapPin, Menu, Sparkles, UsersRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { supabase, categoryEmoji, categoryLabels, type EventCategory, type EventRow } from "@/lib/supabase";

const fallbackEvents: EventRow[] = [
  { id: "sample-1", title: "Coffee, no agenda", description: "A soft landing for a Saturday morning. Come as you are, stay as long as you like.", category: "coffee", city: "Singapore", country: "Singapore", venue: "Tiong Bahru", starts_at: "2026-10-10T10:30:00+08:00", ends_at: "2026-10-10T12:00:00+08:00", capacity: 18, published: true, archived: false },
  { id: "sample-2", title: "The book we never finished", description: "A very low-pressure reading circle for curious people and unfinished books.", category: "reading", city: "London", country: "United Kingdom", venue: "Hackney Library", starts_at: "2026-10-17T14:00:00+01:00", ends_at: "2026-10-17T16:00:00+01:00", capacity: 14, published: true, archived: false },
  { id: "sample-3", title: "Playground yoga", description: "Stretch, breathe, and remember that bodies are for living in—not just carrying laptops.", category: "yoga", city: "Melbourne", country: "Australia", venue: "Fitzroy Gardens", starts_at: "2026-10-24T09:00:00+11:00", ends_at: "2026-10-24T10:15:00+11:00", capacity: 20, published: true, archived: false },
  { id: "sample-4", title: "Paint like nobody is judging", description: "An evening of color, snacks, and permission to make something gloriously imperfect.", category: "art", city: "New York", country: "United States", venue: "Bushwick studio", starts_at: "2026-10-29T19:00:00-04:00", ends_at: "2026-10-29T21:00:00-04:00", capacity: 16, published: true, archived: false },
];

function formatDate(date: string) { return new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(date)); }

export default function Home() {
  const [, navigate] = useLocation();
  const [events, setEvents] = useState<EventRow[]>([]);
  const [city, setCity] = useState("All cities");
  const [category, setCategory] = useState<"all" | EventCategory>("all");
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { let active = true; supabase.from("events").select("*").eq("published", true).gte("starts_at", new Date().toISOString()).order("starts_at").then(({ data }) => { if (active) setEvents(data?.length ? (data as EventRow[]) : fallbackEvents); }); return () => { active = false; }; }, []);
  const visibleEvents = useMemo(() => events.filter((event) => (city === "All cities" || event.city === city) && (category === "all" || event.category === category)), [events, city, category]);
  const cities = ["All cities", ...Array.from(new Set(events.map((event) => event.city)))];
  return (
    <div className="min-h-screen bg-[#fffaf2] text-[#19312f]">
      <header className="sticky top-0 z-30 border-b border-[#d9e6dc]/80 bg-[#fffaf2]/95 backdrop-blur-md"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-3" onClick={() => setMenuOpen(false)}><span className="brand-mark">40U</span><span className="hidden text-sm font-semibold tracking-wide text-[#50716b] sm:inline">social club</span></Link><nav className="hidden items-center gap-2 sm:flex"><a href="#events" className="nav-link">Find your people</a><Link href="/my-registrations" className="nav-link">My plans</Link><Link href="/auth" className="button-outline">Sign in</Link></nav><button className="rounded-full p-3 sm:hidden" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-[#d9e6dc] px-5 pb-5 pt-3 sm:hidden"><div className="flex flex-col gap-2"><a href="#events" className="mobile-nav-link" onClick={() => setMenuOpen(false)}>Find your people</a><Link href="/my-registrations" className="mobile-nav-link">My plans</Link><Link href="/auth" className="button-primary text-center">Sign in</Link></div></div>}</header>
      <main>
        <section className="hero-shell"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16} /> A social club for kids above 40</div><h1>Make room for the part of you that still wants to <em>play.</em></h1><p className="hero-lede">40U is a gentle, grown-up excuse to get out of your head and into a room with good people. No pitching. No networking. No pretending you are not tired.</p><div className="flex flex-wrap gap-3"><a href="#events" className="button-primary">See what’s happening <ArrowRight size={18} /></a><Link href="/auth?mode=signup" className="button-quiet">Join the club</Link></div><p className="hero-note">40U means <strong>you</strong>. It also means <strong>up</strong>.</p></div><div className="hero-art" aria-label="Illustration of a playful sun and abstract shapes"><div className="sun-shape" /><div className="blob blob-one" /><div className="blob blob-two" /><div className="scribble">still<br />curious</div><div className="age-sticker">40+<br /><span>and just<br />getting started</span></div></div></section>
        <section className="intro-strip"><div><p className="eyebrow">The 40U promise</p><h2>Less “what do you do?”<br /><span>More “how are you, really?”</span></h2></div><div className="intro-points"><p><UsersRound size={22} /> Small gatherings with room to be human.</p><p><Sparkles size={22} /> Life-first conversations, not business cards.</p><p><CalendarDays size={22} /> Something on the calendar to look forward to.</p></div></section>
        <section className="mx-auto max-w-6xl px-5 py-10 lg:px-8 lg:py-16" aria-labelledby="club-banner-title"><div className="overflow-hidden rounded-[2rem] border border-[#19312f]/15 bg-[#19312f] shadow-[10px_12px_0_#d8eaa8]"><figure><img src="/manus-storage/40u-life-after-40-banner_f46b9a17.png" alt="A colourful group of adults enjoying a playful outdoor gathering, with the message Life after 40. Refuse to grow up." className="block h-auto w-full" loading="lazy" /><figcaption id="club-banner-title" className="flex flex-wrap items-center justify-between gap-3 px-5 py-4 text-base font-semibold text-[#fffaf2] sm:px-7 sm:text-lg"><span>This is the 40U mood.</span><span className="font-normal text-[#d8eaa8]">Come as you are. Leave your business card at home.</span></figcaption></figure></div></section>
        <section id="events" className="events-section"><div className="section-heading"><div><p className="eyebrow">Open invitations</p><h2>Come out and play</h2><p>Pick a city, pick a mood, or pick the one with the best snacks.</p></div><Badge className="count-badge">{visibleEvents.length} upcoming</Badge></div><div className="filters"><div className="scroll-row">{cities.map((item) => <button key={item} className={`filter-pill ${city === item ? "active" : ""}`} onClick={() => setCity(item)}>{item}</button>)}</div><div className="scroll-row">{(["all", ...Object.keys(categoryLabels)] as const).map((item) => <button key={item} className={`filter-pill ${category === item ? "active" : ""}`} onClick={() => setCategory(item as typeof category)}>{item === "all" ? "Everything" : `${categoryEmoji[item as EventCategory]} ${categoryLabels[item as EventCategory]}`}</button>)}</div></div><div className="event-grid">{visibleEvents.map((event) => <article className="event-card" key={event.id}><div className={`event-card-top category-${event.category}`}><span className="category-icon">{categoryEmoji[event.category]}</span><span>{categoryLabels[event.category]}</span><span className="city-tag">{event.city}</span></div><div className="event-card-body"><h3>{event.title}</h3><p>{event.description}</p><div className="event-meta"><span><CalendarDays size={16} />{formatDate(event.starts_at)}</span><span><MapPin size={16} />{event.venue}</span></div><Button className="button-card" onClick={() => navigate(`/register/${event.id}`)}>I’m interested <ArrowRight size={16} /></Button></div></article>)}</div>{!visibleEvents.length && <div className="empty-state">No gatherings match that combination yet. Try another mood—or host the first one.</div>}</section>
        <section className="closing-cta"><p className="eyebrow">A little reminder</p><h2>You are allowed to have a life that is not only useful.</h2><Link href="/auth?mode=signup" className="button-primary">Make plans with us <ArrowRight size={18} /></Link></section>
      </main><footer className="site-footer"><span className="brand-mark small">40U</span><span>HQ Singapore · growing wherever curious people gather</span><span>© 2026 40U Social Club</span></footer>
    </div>
  );
}
