import { FormEvent, useEffect, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowLeft, CalendarDays, CheckCircle2, MapPin } from "lucide-react";
import { supabase, type EventRow } from "@/lib/supabase";

export default function Register() {
  const [, params] = useRoute("/register/:id"); const [, navigate] = useLocation(); const [event, setEvent] = useState<EventRow | null>(null); const [session, setSession] = useState<any>(null); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [month, setMonth] = useState(""); const [day, setDay] = useState(""); const [error, setError] = useState(""); const [done, setDone] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); if (data.session?.user.email) setEmail(data.session.user.email); if (data.session?.user.user_metadata?.name) setName(data.session.user.user_metadata.name); }); if (params?.id?.startsWith("sample-")) return; supabase.from("events").select("*").eq("id", params?.id).single().then(({ data }) => setEvent(data as EventRow)); }, [params?.id]);
  async function submit(e: FormEvent) { e.preventDefault(); if (!session) { navigate(`/auth?mode=signin&next=/register/${params?.id}`); return; } setBusy(true); setError(""); const { error: insertError } = await supabase.from("registrations").insert({ event_id: params?.id, user_id: session.user.id, name, email, birthday_month: Number(month), birthday_day: Number(day) }); setBusy(false); if (insertError) setError(insertError.message.includes("duplicate") ? "You are already on the list for this one." : insertError.message); else setDone(true); }
  if (!session) return <div className="min-h-screen bg-[#fffaf2] px-5 py-12"><div className="mx-auto max-w-lg"><Link href="/" className="inline-flex items-center gap-2 font-bold text-[#50716b]"><ArrowLeft size={18} /> Back to events</Link><div className="mt-12 rounded-[2rem] bg-[#19312f] p-7 text-[#fffaf2] sm:p-10"><p className="eyebrow !text-[#f7c25b]">One tiny step</p><h1 className="!text-[3.4rem]">Sign in to make plans.</h1><p className="mb-7 text-[#dbe8d8]">Registration is for members only, so the people in the room can know they are meeting other humans—not collecting leads.</p><Link href={`/auth?mode=signin&next=/register/${params?.id}`} className="button-primary">Continue to sign in</Link></div></div></div>;
  if (done) return <div className="min-h-screen bg-[#fffaf2] px-5 py-12"><div className="mx-auto max-w-lg"><div className="rounded-[2rem] bg-[#c8dc43] p-8 text-[#19312f] sm:p-12"><CheckCircle2 size={42} /><p className="eyebrow !text-[#19312f] mt-5">You are on the list</p><h1 className="!text-[3.3rem]">See you there.</h1><p className="mb-7">Your place is saved. You can always see your plans from the 40U home page.</p><Link href="/my-registrations" className="button-outline">View my plans</Link></div></div></div>;
  return <div className="min-h-screen bg-[#fffaf2] px-5 py-8"><div className="mx-auto max-w-2xl"><Link href="/" className="inline-flex items-center gap-2 font-bold text-[#50716b]"><ArrowLeft size={18} /> Back to events</Link><div className="mt-10 grid gap-6 md:grid-cols-[.85fr_1.15fr]"><div className="rounded-[2rem] bg-[#f7c25b] p-7"><p className="eyebrow !text-[#19312f]">Your invitation</p><h1 className="!text-[3.2rem]">Kids above 40 welcome.</h1><p>We do not ask for your age. We simply ask that you bring your real self, a little curiosity, and an appetite for being around people.</p><p className="mt-5 text-sm font-bold">Birthday month/day helps us celebrate you. No birth year. Ever.</p></div><div className="rounded-[2rem] border border-[#d9e6dc] bg-white p-6 sm:p-8"><h2 className="mb-5 font-serif text-3xl">Save your seat</h2>{event && <div className="mb-6 rounded-2xl bg-[#edf4dc] p-4"><h3 className="font-serif text-2xl">{event.title}</h3><p className="mt-2 flex items-center gap-2 text-sm text-[#50716b]"><CalendarDays size={16} />{new Date(event.starts_at).toLocaleString()}</p><p className="mt-1 flex items-center gap-2 text-sm text-[#50716b]"><MapPin size={16} />{event.venue}, {event.city}</p></div>}{error && <div className="mb-4 rounded-xl bg-[#fce4df] p-4 text-[#9b3f35]">{error}</div>}<form onSubmit={submit} className="space-y-4"><label className="field-label">Name<input required className="field-input" value={name} onChange={(e) => setName(e.target.value)} /></label><label className="field-label">Email<input required type="email" className="field-input" value={email} onChange={(e) => setEmail(e.target.value)} /></label><div className="grid grid-cols-2 gap-3"><label className="field-label">Birthday month<select required className="field-input" value={month} onChange={(e) => setMonth(e.target.value)}><option value="">Month</option>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>{new Date(2000, i, 1).toLocaleString(undefined, { month: "long" })}</option>)}</select></label><label className="field-label">Birthday day<select required className="field-input" value={day} onChange={(e) => setDay(e.target.value)}><option value="">Day</option>{Array.from({ length: 31 }, (_, i) => <option key={i + 1} value={i + 1}>{i + 1}</option>)}</select></label></div><button disabled={busy} className="button-primary w-full border-0">{busy ? "Saving your seat…" : "Register for this gathering"}</button></form></div></div></div></div>;
}
